# Generated by Django 4.2.3 on 2023-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_receipe_reciepe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='reciepe_image',
            field=models.ImageField(upload_to='receipe'),
        ),
    ]
